wandb_version: 1

batch_size:
  value: 64
early_stopping_patience:
  value: 5
latent_dim:
  value: 16
learning_rate:
  value: 0.0009009124880598386
num_epochs:
  value: 50
optimizer:
  value: adam
scheduler_factor:
  value: 0.5
scheduler_patience:
  value: 5
weight_decay:
  value: 0.001
