wandb_version: 1

batch_size:
  value: 128
early_stopping_patience:
  value: 5
latent_dim:
  value: 32
learning_rate:
  value: 0.0008650181253887037
num_epochs:
  value: 50
optimizer:
  value: adam
scheduler_factor:
  value: 0.5
scheduler_patience:
  value: 5
weight_decay:
  value: 1.0e-05
