_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 1
                - 23
                - 55
            "4": 3.12.2
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": darwin-arm64
batch_size:
    value: 128
early_stopping_patience:
    value: 5
latent_dim:
    value: 8
learning_rate:
    value: 0.0001674185243766176
num_epochs:
    value: 50
optimizer:
    value: adam
scheduler_factor:
    value: 0.5
scheduler_patience:
    value: 5
weight_decay:
    value: 1e-05
